name: h4
description: A minimal HTTP library for dart
version: 1.0.0
repository: https://github.com/iyifr/h4

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  extension_type_unions: ^1.0.10
  http2: ^2.3.0
  meta: ^1.15.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
