name: h4
description: A minimal HTTP framework for building elegant server applications.
version: 0.1.4
repository: https://github.com/iyifr/h4

environment:
  sdk: ^3.3.0

topics:
  - http-framework
  - server
  - api

executables:
  init: init

# Add regular dependencies here.
dependencies:
  meta: ^1.15.0
  compute: ^1.0.2
  logging: ^1.2.0
  either_dart: ^1.0.0
  http: ^1.2.1
  args: ^2.5.0
  console: ^4.1.0
  path: ^1.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  dio: ^5.4.3+1
