name: h4
description: A minimal HTTP framework for building elegant server applications.
version: 0.0.3
repository: https://github.com/iyifr/h4

environment:
  sdk: ^3.3.0

topics:
  - http
  - server
  - api

# Add regular dependencies here.
dependencies:
  meta: ^1.15.0
  # path: ^1.8.0
  logger: ^2.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  dio: ^5.4.3+1
