name: h4
description: A ligthweight, loosely opinionated http framework for dart.
version: 0.4.3
repository: https://github.com/iyifr/h4

environment:
  sdk: ^3.3.0

topics:
  - http-framework
  - server
  - api

executables:
  init: init
  start: start

# Add regular dependencies here.
dependencies:
  meta: ^1.15.0
  logging: ^1.2.0
  http: ^1.2.1
  args: ^2.5.0
  console: ^4.1.0
  path: ^1.9.0
  watcher: ^1.1.0
  mime: ^1.0.6

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  dio: ^5.4.3+1
